### ISSUE TITLE
Adjust regex for semver test

### ISSUE THREAD

**Issue by nicolasguenther** [spocke/grunt-nuget-pack#2]
First of all thank you for this grunt plugin. Just what i needed!

Sadly i can't use it to bundle my project because it doesn't support semver version numbers like i.e. `1.0.0-beta+exp.sha.5114f85`.

See semver specification [Semver Specification](http://semver.org/) and [Semver Regex](https://github.com/sindresorhus/semver-regex).

**Comment by spocke** [comment]
Fixed this one thanks for the report.
